export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE";
export const SORT_ORDER_PRODUCT_BY_PRICE = "SORT_ORDER_PRODUCT_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
